name: qgridnext-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipywidgets=8.1.1
  - pandas=2.2.0
  - jupyterlab=4.1.8
  - notebook=7.1.3
  - voila=0.5.6
  - pytest
  - nodejs=20
  - pyarrow
